modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="mrm"
version="1.0.0"
displayName="MyRandomModels"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="edwin, MCreator"

[[dependencies.mrm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



